################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/CMSIS/DSP/Source/FilteringFunctions/%.o Drivers/CMSIS/DSP/Source/FilteringFunctions/%.su: ../Drivers/CMSIS/DSP/Source/FilteringFunctions/%.c Drivers/CMSIS/DSP/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H7A3xxQ -c -I../Core/Inc -I"/Users/xdd/STM32CubeIDE/workspace_1.10.1/OpenNNA_STM32H7A3_Demo_Example/Middlewares/OpenNNA2.0/core" -I"/Users/xdd/STM32CubeIDE/workspace_1.10.1/OpenNNA_STM32H7A3_Demo_Example/Middlewares/OpenNNA2.0/model" -I"/Users/xdd/STM32CubeIDE/workspace_1.10.1/OpenNNA_STM32H7A3_Demo_Example/Middlewares/OpenNNA2.0/operator" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-FilteringFunctions

clean-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-FilteringFunctions:
	-$(RM) ./Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d
	-$(RM) ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.su
	-$(RM) ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o
	-$(RM) ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-FilteringFunctions

